compatibility: FORWARD_TRANSITIVE

subjects:
  - name: dependent-ThisDependsOnTemporal-value
    file: dependent/ThisDependsOnTemporal.avsc
    compatibility: BACKWARD

#  - name: without-compatiblity
#    file: without_compatibility.avsc
#
#  - name: foo-proto-value
#    file: foo.proto
#    type: PROTOBUF
#
#  - name: json-schema-value
#    file: foo.json
#    type: JSON